config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get "/signup", to: "users#new"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts,      only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Sample App
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="navbarId">
    
  
    <div class="container-fluid">
    
      <%= link_to "sample app", root_path, id: "logo", class: "navbar-brand" %>
    
      <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarMenu">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarMenu">        
         <ul class="navbar-nav ml-auto">
          <li class="nav-item"><%= link_to "Home",   root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Help",   help_path, class: "nav-link" %></li>
          <% if logged_in? %>
            <li class="nav-item"><%= link_to  "Users", users_path, class: "nav-link" %></li>
            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li class="dropdown-item"><%= link_to  "Profile", current_user %></li>
                <li class="dropdown-item"><%= link_to  "Settings", edit_user_path(current_user) %></li>
                <div class="dropdown-divider"></div>
                <li class="dropdown-item">
                  <%= link_to  "Log out", logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
          <li class="nav-item"><%= link_to "Log in", login_path, class: "nav-link" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                          'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= render  "layouts/rails_default" %>
    <%= render  "layouts/shim" %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>